services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    container_name: boilerplate-postgres
    volumes:
    - ./pgdata:/var/lib/postgresql/data
    ports:
    - "${DB_PORT}:5432"
    networks:
    - boilerplate-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 0
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boilerplate-nestjs
    environment:
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    volumes:
      - ./src:/app/src
    networks:
      - boilerplate-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 10s
      timeout: 5s
      retries: 3
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: boilerplate_pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_HOST_PORT}:${PGADMIN_CONTAINER_PORT}"
    depends_on:
      - db
    networks:
      - boilerplate-net

networks:
  boilerplate-net:
    driver: bridge
